services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: atlas-backend:prod
    command: sh -c "npm run migrate && node dist/src/server.js"

  backend-worker:
    image: atlas-backend:prod
    command: node dist/src/workers.js

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000/api
    image: atlas-frontend:prod
    command: npm run start
